export type ICity = {
  code: string;
  municipality: string;
  country: string;
  region: number;
  type: string;
  state: string;
  name: string;
};

export const CITIES = [
  {
    code: "532101",
    municipality: "01",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "21",
    name: "Sandino",
  },
  {
    code: "532102",
    municipality: "02",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "21",
    name: "Mantua",
  },
  {
    code: "532103",
    municipality: "03",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "21",
    name: "Minas de Matahambre",
  },
  {
    code: "532104",
    municipality: "04",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "21",
    name: "Viñales",
  },
  {
    code: "532105",
    municipality: "05",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "21",
    name: "La Palma",
  },
  {
    code: "532106",
    municipality: "06",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "21",
    name: "Los Palacios",
  },
  {
    code: "532107",
    municipality: "07",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "21",
    name: "Consolación del sur",
  },
  {
    code: "532108",
    municipality: "08",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "21",
    name: "Pinar del Río",
  },
  {
    code: "532109",
    municipality: "09",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "21",
    name: "San Luis",
  },
  {
    code: "532110",
    municipality: "10",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "21",
    name: "San Juan y Martínez",
  },
  {
    code: "532111",
    municipality: "11",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "21",
    name: "Guane",
  },

  {
    code: "532201",
    municipality: "01",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "22",
    name: "Bahía Honda",
  },
  {
    code: "532202",
    municipality: "02",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "22",
    name: "Mariel",
  },
  {
    code: "532203",
    municipality: "03",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "22",
    name: "Guanajay",
  },
  {
    code: "532204",
    municipality: "04",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "22",
    name: "Caimito",
  },
  {
    code: "532205",
    municipality: "05",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "22",
    name: "Bauta",
  },
  {
    code: "532206",
    municipality: "06",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "22",
    name: "San Antonio de los Baños",
  },
  {
    code: "532207",
    municipality: "07",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "22",
    name: "Güira de Melena",
  },
  {
    code: "532208",
    municipality: "08",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "22",
    name: "Alquízar",
  },
  {
    code: "532209",
    municipality: "09",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "22",
    name: "Artemisa",
  },
  {
    code: "532210",
    municipality: "10",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "22",
    name: "Candelaria",
  },
  {
    code: "532211",
    municipality: "11",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "22",
    name: "San Cristóbal",
  },

  {
    name: "Habana del Este",
    code: "532306",
    municipality: "06",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "Centro Habana",
    code: "532303",
    municipality: "03",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "Regla",
    code: "532305",
    municipality: "05",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "Plaza de la Revolución",
    code: "532302",
    municipality: "02",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "La Habana Vieja",
    code: "532304",
    municipality: "04",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "Cerro",
    code: "532310",
    municipality: "10",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "Diez de Octubre",
    code: "532309",
    municipality: "09",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "Guanabacoa",
    code: "532307",
    municipality: "07",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "San Miguel del Padrón",
    code: "532308",
    municipality: "08",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "Playa",
    code: "532301",
    municipality: "01",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "Arroyo Naranjo",
    code: "532314",
    municipality: "14",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "Boyeros",
    code: "532313",
    municipality: "13",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "Marianao",
    code: "532311",
    municipality: "11",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "Cotorro",
    code: "532315",
    municipality: "15",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },
  {
    name: "La Lisa",
    code: "532312",
    municipality: "12",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "23",
  },

  {
    name: "Santa Cruz del Norte",
    code: "532404",
    municipality: "04",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "24",
  },
  {
    name: "San José de las Lajas",
    code: "532402",
    municipality: "02",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "24",
  },
  {
    name: "Jaruco",
    code: "532403",
    municipality: "03",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "24",
  },
  {
    name: "Madruga",
    code: "532405",
    municipality: "05",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "24",
  },
  {
    name: "Bejucal",
    code: "532401",
    municipality: "01",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "24",
  },
  {
    name: "Quivicán",
    code: "532411",
    municipality: "11",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "24",
  },
  {
    name: "Güines",
    code: "532408",
    municipality: "08",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "24",
  },
  {
    name: "San Nicolás",
    code: "532407",
    municipality: "07",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "24",
  },
  {
    name: "Nueva Paz",
    code: "532406",
    municipality: "06",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "24",
  },
  {
    name: "Batabanó",
    code: "532410",
    municipality: "10",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "24",
  },
  {
    name: "Melena del Sur",
    code: "532409",
    municipality: "09",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "24",
  },

  {
    name: "Martí",
    code: "532503",
    municipality: "03",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Cárdenas",
    code: "532502",
    municipality: "02",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Matanzas",
    code: "532501",
    municipality: "01",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Limonar",
    code: "532508",
    municipality: "08",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Unión de Reyes",
    code: "532509",
    municipality: "09",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Perico",
    code: "532505",
    municipality: "05",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Jovellanos",
    code: "532506",
    municipality: "06",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Pedro Betancourt",
    code: "532507",
    municipality: "07",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Los Arabos",
    code: "532513",
    municipality: "13",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Colón",
    code: "532504",
    municipality: "04",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Jagüey Grande",
    code: "532511",
    municipality: "11",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Calimete",
    code: "532512",
    municipality: "12",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },
  {
    name: "Cienaga de Zapata",
    code: "532510",
    municipality: "10",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "25",
  },

  {
    name: "Sagua La Grande",
    code: "532603",
    municipality: "03",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Corralillo",
    code: "532601",
    municipality: "01",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Quemado de Güines",
    code: "532602",
    municipality: "02",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Santo Domingo",
    code: "532611",
    municipality: "11",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Cifuentes",
    code: "532610",
    municipality: "10",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Ranchuelo",
    code: "532612",
    municipality: "12",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Santa Clara",
    code: "532609",
    municipality: "09",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Manicaragua",
    code: "532613",
    municipality: "13",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Encrucijada",
    code: "532604",
    municipality: "04",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Camajuaní",
    code: "532605",
    municipality: "05",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Caibarién",
    code: "532606",
    municipality: "06",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Remedios",
    code: "532607",
    municipality: "07",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },
  {
    name: "Placetas",
    code: "532608",
    municipality: "08",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "26",
  },

  {
    name: "Rodas",
    code: "532702",
    municipality: "02",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "27",
  },
  {
    name: "Lajas",
    code: "532704",
    municipality: "04",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "27",
  },
  {
    name: "Aguada de Pasajeros",
    code: "532701",
    municipality: "01",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "27",
  },
  {
    name: "Palmira",
    code: "532703",
    municipality: "03",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "27",
  },
  {
    name: "Cruces",
    code: "532705",
    municipality: "05",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "27",
  },
  {
    name: "Cumanayagua",
    code: "532706",
    municipality: "06",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "27",
  },
  {
    name: "Cienfuegos",
    code: "532707",
    municipality: "07",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "27",
  },
  {
    name: "Abreus",
    code: "532708",
    municipality: "08",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "27",
  },

  {
    name: "Trinidad",
    code: "532806",
    municipality: "06",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "28",
  },
  {
    name: "Yaguajay",
    code: "532801",
    municipality: "01",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "28",
  },
  {
    name: "Cabaiguán",
    code: "532804",
    municipality: "04",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "28",
  },
  {
    name: "Fomento",
    code: "532805",
    municipality: "05",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "28",
  },
  {
    name: "Taguasco",
    code: "532803",
    municipality: "03",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "28",
  },
  {
    name: "Jatibonico",
    code: "532802",
    municipality: "02",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "28",
  },
  {
    name: "Sancti Spíritus",
    code: "532807",
    municipality: "07",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "28",
  },
  {
    name: "La Sierpe",
    code: "532808",
    municipality: "08",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "28",
  },

  {
    name: "Chambas",
    code: "532901",
    municipality: "01",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "29",
  },
  {
    name: "Morón",
    code: "532902",
    municipality: "02",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "29",
  },
  {
    name: "Florencia",
    code: "532906",
    municipality: "06",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "29",
  },
  {
    name: "Ciro Redondo",
    code: "532905",
    municipality: "05",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "29",
  },
  {
    name: "Bolivia",
    code: "532903",
    municipality: "03",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "29",
  },
  {
    name: "Primero de Enero",
    code: "532904",
    municipality: "04",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "29",
  },
  {
    name: "Majagua",
    code: "532907",
    municipality: "07",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "29",
  },
  {
    name: "Ciego de Ávila",
    code: "532908",
    municipality: "08",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "29",
  },
  {
    name: "Baraguá",
    code: "532910",
    municipality: "10",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "29",
  },
  {
    name: "Venezuela",
    code: "532909",
    municipality: "09",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "29",
  },

  {
    name: "Nuevitas",
    code: "533005",
    municipality: "05",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Esmeralda",
    code: "533002",
    municipality: "02",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Sierra de Cubitas",
    code: "533003",
    municipality: "03",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Minas",
    code: "533004",
    municipality: "04",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Carlos Manuel de Céspedes",
    code: "533001",
    municipality: "01",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Florida",
    code: "533009",
    municipality: "09",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Camagüey",
    code: "533008",
    municipality: "08",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Guáimaro",
    code: "533006",
    municipality: "06",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Sibanicú",
    code: "533007",
    municipality: "07",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Vertientes",
    code: "533010",
    municipality: "10",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Jimaguayú",
    code: "533011",
    municipality: "11",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Santa Cruz del Sur",
    code: "533013",
    municipality: "13",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },
  {
    name: "Najasa",
    code: "533012",
    municipality: "12",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "30",
  },

  {
    name: "Manatí",
    code: "533101",
    municipality: "01",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "31",
  },
  {
    name: "Jesús Menéndez",
    code: "533103",
    municipality: "03",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "31",
  },
  {
    name: "Puerto Padre",
    code: "533102",
    municipality: "02",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "31",
  },
  {
    name: "Las Tunas",
    code: "533105",
    municipality: "05",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "31",
  },
  {
    name: "Jobabo",
    code: "533106",
    municipality: "06",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "31",
  },
  {
    name: "Colombia",
    code: "533107",
    municipality: "07",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "31",
  },
  {
    name: "Amancio",
    code: "533108",
    municipality: "08",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "31",
  },
  {
    name: "Majibacoa",
    code: "533104",
    municipality: "04",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
    state: "31",
  },

  {
    name: "Banes",
    code: "533203",
    municipality: "03",
    state: "32",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
  },
  {
    name: "Gibara",
    code: "533201",
    municipality: "01",
    state: "32",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
  },
  {
    name: "Rafael Freyre",
    code: "533202",
    municipality: "02",
    state: "32",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
  },
  {
    name: "Calixto García",
    code: "533207",
    municipality: "07",
    state: "32",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
  },
  {
    name: "Holguín",
    code: "533206",
    municipality: "06",
    state: "32",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
  },
  {
    name: "Báguanos",
    code: "533205",
    municipality: "05",
    state: "32",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
  },
  {
    name: "Antilla",
    code: "533204",
    municipality: "04",
    state: "32",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
  },
  {
    name: "Mayarí",
    code: "533211",
    municipality: "11",
    state: "32",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
  },
  {
    name: "Cacocum",
    code: "533208",
    municipality: "08",
    state: "32",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
  },
  {
    name: "Moa",
    code: "533214",
    municipality: "14",
    state: "32",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
  },
  {
    name: "Frank País",
    code: "533212",
    municipality: "12",
    state: "32",
    country: "53",
    region: 1,
    type: "MUNICIPALITY",
  },
  {
    name: "Cueto",
    code: "533210",
    municipality: "10",
    state: "32",
    country: "53",
  },
  {
    name: "Urbano Noris",
    code: "533209",
    municipality: "09",
    state: "32",
    country: "53",
  },
  {
    name: "Sagua de Tánamo",
    code: "533213",
    municipality: "13",
    state: "32",
    country: "53",
  },

  {
    name: "Río Cauto",
    code: "533301",
    municipality: "01",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Cauto Cristo",
    code: "533302",
    municipality: "02",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Bayamo",
    code: "533304",
    municipality: "04",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Jiguaní",
    code: "533303",
    municipality: "03",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Yara",
    code: "533305",
    municipality: "05",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Manzanillo",
    code: "533306",
    municipality: "06",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Guisa",
    code: "533313",
    municipality: "13",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Buey Arriba",
    code: "533312",
    municipality: "12",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Bartolomé Masó",
    code: "533311",
    municipality: "11",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Media Luna",
    code: "533308",
    municipality: "08",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Niquero",
    code: "533309",
    municipality: "09",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Pilón",
    code: "533310",
    municipality: "10",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },
  {
    name: "Campechuela",
    code: "533307",
    municipality: "07",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "33",
  },

  {
    name: "Segundo Frente",
    code: "533404",
    state: "34",
    municipality: "04",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
  },
  {
    name: "Mella",
    code: "533402",
    state: "34",
    municipality: "02",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
  },
  {
    name: "Contramaestre",
    code: "533401",
    state: "34",
    municipality: "01",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
  },
  {
    name: "San Luis",
    code: "533403",
    state: "34",
    municipality: "03",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
  },
  {
    name: "Palma Soriano",
    code: "533407",
    state: "34",
    municipality: "07",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
  },
  {
    name: "Songo La Maya",
    code: "533405",
    state: "34",
    municipality: "05",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
  },
  {
    name: "Tercer Frente",
    code: "533408",
    state: "34",
    municipality: "08",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
  },
  {
    name: "Santiago de Cuba",
    code: "533406",
    state: "34",
    municipality: "06",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
  },
  {
    name: "Guamá",
    code: "533409",
    state: "34",
    municipality: "09",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
  },

  {
    name: "Guantánamo",
    code: "533509",
    municipality: "09",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "35",
  },
  {
    name: "Yateras",
    code: "533503",
    municipality: "03",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "35",
  },
  {
    name: "El Salvador",
    code: "533501",
    municipality: "01",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "35",
  },
  {
    name: "Manuel Tames",
    code: "533502",
    municipality: "02",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "35",
  },
  {
    name: "Niceto Pérez",
    code: "533510",
    municipality: "10",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "35",
  },
  {
    name: "Caimanera",
    code: "533508",
    municipality: "08",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "35",
  },
  {
    name: "San Antonio del Sur",
    code: "533507",
    municipality: "07",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "35",
  },
  {
    name: "Baracoa",
    code: "533504",
    municipality: "04",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "35",
  },
  {
    name: "Imías",
    code: "533506",
    municipality: "06",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "35",
  },
  {
    name: "Maisí",
    code: "533505",
    municipality: "05",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "35",
  },
  {
    code: "534001",
    municipality: "01",
    region: 1,
    country: "53",
    type: "MUNICIPALITY",
    state: "40",
    name: "Isla de la Juventud",
  },
];
