export type IState = {
  name: string;
  country: string;
  state: string;
  code: string;
  region: number;
  type: string;
  acronym: string;
};

export const STATES: IState[] = [
  {
    name: "Pinar del Río",
    country: "53",
    state: "21",
    code: "5321",
    region: 1,
    type: "STATE",
    acronym: "PRI",
  },
  {
    name: "Artemisa",
    country: "53",
    state: "22",
    code: "5322",
    region: 1,
    type: "STATE",
    acronym: "ART",
  },
  {
    name: "La Habana",
    country: "53",
    state: "23",
    code: "5323",
    region: 1,
    type: "STATE",
    acronym: "HAB",
  },
  {
    name: "Mayabeque",
    country: "53",
    state: "24",
    code: "5324",
    region: 1,
    type: "STATE",
    acronym: "MAY",
  },
  {
    name: "Matanzas",
    country: "53",
    state: "25",
    code: "5325",
    region: 1,
    type: "STATE",
    acronym: "MTZ",
  },
  {
    name: "Villa Clara",
    country: "53",
    state: "26",
    code: "5326",
    region: 1,
    type: "STATE",
    acronym: "VCL",
  },
  {
    name: "Cienfuegos",
    country: "53",
    state: "27",
    code: "5327",
    region: 1,
    type: "STATE",
    acronym: "CFG",
  },
  {
    name: "Sancti Spíritus",
    country: "53",
    state: "28",
    code: "5328",
    region: 1,
    type: "STATE",
    acronym: "SSP",
  },
  {
    name: "Ciego de Ávila",
    country: "53",
    state: "29",
    code: "5329",
    region: 1,
    type: "STATE",
    acronym: "CAV",
  },
  {
    name: "Camagüey",
    country: "53",
    state: "30",
    code: "5330",
    region: 1,
    type: "STATE",
    acronym: "CAM",
  },
  {
    name: "Las Tunas",
    country: "53",
    state: "31",
    code: "5331",
    region: 1,
    type: "STATE",
    acronym: "LTU",
  },
  {
    name: "Holguín",
    country: "53",
    state: "32",
    code: "5332",
    region: 1,
    type: "STATE",
    acronym: "HOL",
  },
  {
    name: "Granma",
    state: "33",
    code: "5333",
    region: 1,
    country: "53",
    type: "STATE",
    acronym: "GRM",
  },
  {
    name: "Santiago de Cuba",
    country: "53",
    state: "34",
    code: "5334",
    region: 1,
    type: "STATE",
    acronym: "SCU",
  },
  {
    name: "Guantánamo",
    country: "53",
    state: "35",
    code: "5335",
    region: 1,
    type: "STATE",
    acronym: "GTM",
  },
  {
    name: "Isla de la Juventud",
    country: "53",
    state: "36",
    code: "5336",
    region: 1,
    type: "STATE",
    acronym: "ISJ",
  },
];
