import "@repo/ui/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { CompleteBusiness } from "@repo/model/zod/index";
import { getCurrentBusiness } from "@repo/model/repository/business";
import { Header } from "../../components/layout/header";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  const business = (await getCurrentBusiness()) as CompleteBusiness;

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex flex-col min-h-dvh pb-10">
          <NextIntlClientProvider messages={messages}>
            <Header business={business} locale={locale} />
            <main className="flex-1 container pt-20 md:py-16 lg:py-20">
              {children}
            </main>
          </NextIntlClientProvider>
        </div>
      </body>
    </html>
  );
}
