import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Toaster } from "@repo/ui/components/ui/toaster";
import { TooltipProvider } from "@repo/ui/components/ui/tooltip";
import { LayoutMain } from "@repo/ui/layouts/backoffice/main";
import { mainMenu, profileMenu, secondaryMenu } from "../config/menu";
import localFont from "next/font/local";
import { businessRepository } from "@repo/model/repositories/business";
import { Item } from "@repo/ui/layouts/backoffice/business.switch";
import { redirect } from "next/navigation";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

// Only for testing
const breadcrumbItems = [
  {
    title: "Dashboard",
    link: "/",
  },
  {
    title: "Acme Inc",
    link: "/post",
  },
];

export default async function RootLayout({
  children,
  params: { businessId },
}: {
  children: React.ReactNode;
  params: { businessId: string };
}) {
  const business = await businessRepository.getByUser("");
  const onChangeBusiness = async (businessId: string) => {
    "use server";
    await redirect(`/${businessId}`);
  };
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TooltipProvider>
          <LayoutMain
            menuItems={mainMenu(businessId)}
            secondaryMenu={secondaryMenu}
            userImage="/placeholder-user.jpg"
            userMenuItems={profileMenu}
            breadcrumbItems={breadcrumbItems}
            businessId={businessId}
            ph="Negocio..."
            business={business as Item[]}
            onChange={onChangeBusiness}
          >
            {children}
          </LayoutMain>
          <Toaster />
        </TooltipProvider>
      </body>
    </html>
  );
}
