import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Toaster } from "@repo/ui/components/ui/toaster";
import { TooltipProvider } from "@repo/ui/components/ui/tooltip";
import { LayoutMain } from "@repo/ui/layouts/backoffice/main";
import { mainMenu, profileMenu, secondaryMenu } from "./config/menu";
import localFont from 'next/font/local';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

// Only for testing
const breadcrumbItems = [
  {
    title: "Dashboard",
    link: "/",
  },
  {
    title: "Acme Inc",
    link: "/post",
  },
]

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TooltipProvider>
          <LayoutMain
            menuItems={mainMenu}
            secondaryMenu={secondaryMenu}
            userImage="/placeholder-user.jpg"
            userMenuItems={profileMenu}
            breadcrumbItems={breadcrumbItems}
          >
            {children}
          </LayoutMain>
          <Toaster />
        </TooltipProvider>
      </body>
    </html>
  );
}
